import express from 'express';
import dotenv from 'dotenv';
import bodyParser from 'body-parser';
import cors from 'cors';
import pool from './db';
import authRoutes from './routes/auth';
import productsRoutes from './routes/products';
import ordersRoutes from './routes/orders';
import batchesRoutes from './routes/batches';
import integrationsRoutes from './routes/integrations';
import availabilityRoutes from './routes/availability';
dotenv.config();
const app = express();
app.use(cors()); app.use(bodyParser.json());
app.use('/api/auth', authRoutes);
app.use('/api/products', productsRoutes);
app.use('/api/orders', ordersRoutes);
app.use('/api/batches', batchesRoutes);
app.use('/api/integrations', integrationsRoutes);
app.use('/api/check-availability', availabilityRoutes);
app.get('/', (req,res)=>res.json({status:'ok'}));
const port = process.env.PORT||4000; app.listen(port, ()=>console.log('listening', port));
